version: 2

sources:
    - name: KEVANS_SRC
      description: "Test Src Table"
      database: KEVANS_TF_DEMO
      schema: PUBLIC
      tables:
        - name: HYBRID_TABLE
          description: 'Test Table'
          columns:
          - name: ID
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
