
version: 2

sources:
    - name: TEST_SRC
      description: "Test Src Table"
      database: kevans_src
      schema: test
      columns:
          - name: TEST_CODE
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: TEST_NAME
            description: "The primary key for this table"
          - name: TEST_DESC
            description: "The primary key for this table"
          - name: SEQ
            description: "The primary key for this table"