version: 2

sources:
    - name: KEVANS_SRC
      description: "Test Src Table"
      database: kevans_src
      schema: test
      tables:
        - name: TEST_SRC
          description: 'Test Table'
          columns:
          - name: TEST_CODE
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
